### PR TITLE
Employer Login

### LINKED ISSUE #85: Allow Employers to Sign Up and Sign In
Currently, only seekers can sign up and sign in. 

Develop functionality allowing Employers to Sign Up and Sign In

### PR DESCRIPTION
**Pull request by TheBrockstar**
# Description

Both Employers and Seekers can now Sign Up and Sign In. I also had to adjust the employer post endpoint in order to make this possible, as it wasn't set up to receive the custom token from the auth middleware. 

Resolves #85

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Change status
- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A: Signed up and Logged in as an employer.
- [x] Test B: Logged out and back in as an employer.
- [x] Test C: Checked database for changes.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by easyra — APPROVED** [review]
looks great

**Review by easyra — COMMENTED** [review]
We need to resolve the merge conflicts before me merge though

**Review by easyra — DISMISSED** [review]
merge conflict

**Review by Austinlp4 — APPROVED** [review]
Looks good

**Pull request merged**
